<?php if(isset($this->messages) && count($this->messages)){ 
	$messages = $this->messages;
	if(isset($messages['success']))
	{
		echo '<div class="success" style="color:green">'.$messages['success'].'</div>';
	}else if(isset($messages['failed'])){
		echo '<div class="failed" style="color:red">'.$messages['failed'].'</div>';
	}	
}
?>
<form name="login" action="<?php echo $this->BaseUrl(); ?>/admin/index/login-check" method="post" >
<input type="text" name="email" required  />
<input type="password" name="password" required  />
<input type="submit" value="Submit"  />
</form>